SystemDontHaveSolution_08/09/2025_6837: [Error: El sistema de ecuaciones tiene soluciones infinitas o no tiene solución / coefficients_shape: (3, 3), independents_shape: (3,) / C:\Users\andre\Desktop\calculo\project calculo\CalcNum3era\Numerical-Computing-Project-master\Apps\NumericalMethods\Solvers\MatrixOperators\SystemOfEquationsSolver.py: linea 160 / gaussJordanFullPivoting]
SystemDontHaveSolution_08/09/2025_3751: [Error: El sistema de ecuaciones tiene soluciones infinitas o no tiene solución / ['A', 'B', 'C'] / C:\Users\andre\Desktop\calculo\project calculo\CalcNum3era\Numerical-Computing-Project-master\Apps\DataVisualization\Methods\RandomGraphUtils.py: linea 81 / solvePoints]
TypeError_08/09/2025_4368: ['NoneType' object is not iterable / None / C:\Users\andre\Desktop\calculo\project calculo\CalcNum3era\Numerical-Computing-Project-master\Apps\DataVisualization\Methods\RandomGraphUtils.py: linea 93 / setPointsGroup]
TypeError_08/09/2025_3673: ['NoneType' object is not iterable / 'NoneType' object is not iterable / C:\Users\andre\Desktop\calculo\project calculo\CalcNum3era\Numerical-Computing-Project-master\Apps\DataVisualization\Methods\GraphVisualizer.py: linea 29 / plotPointsAndDistances3D]
TypeError_08/09/2025_5952: [object of type 'NoneType' has no len() / object of type 'NoneType' has no len() / C:\Users\andre\Desktop\calculo\project calculo\CalcNum3era\Numerical-Computing-Project-master\Apps\Common\Composables\MathReport.py: linea 103 / writeSystemsAndSolutions]
TypeError_08/09/2025_5935: [object of type 'NoneType' has no len() / C:\Users\andre\Desktop\calculo\project calculo\CalcNum3era\Numerical-Computing-Project-master\Storage\Results\19dc84ad_matriz1_19dc84ad.txt_20250908_3bd318e4.txt / C:\Users\andre\Desktop\calculo\project calculo\CalcNum3era\Numerical-Computing-Project-master\Apps\Common\Composables\MathReport.py: linea 176 / writeDistancesBetweenPoints]
TypeError_08/09/2025_6848: ['NoneType' object is not iterable / randomGraph view / C:\Users\andre\Desktop\calculo\project calculo\CalcNum3era\Numerical-Computing-Project-master\Apps\DataVisualization\views.py: linea 62 / randomGraph]
SystemDontHaveSolution_10/09/2025_5722: [Error: El sistema de ecuaciones tiene soluciones infinitas o no tiene solución / coefficients_shape: (3, 3), independents_shape: (3,) / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\NumericalMethods\Solvers\MatrixOperators\SystemOfEquationsSolver.py: linea 160 / gaussJordanFullPivoting]
SystemDontHaveSolution_10/09/2025_5262: [Error: El sistema de ecuaciones tiene soluciones infinitas o no tiene solución / ['A', 'B', 'C'] / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\Methods\RandomGraphUtils.py: linea 81 / solvePoints]
TypeError_10/09/2025_7539: ['NoneType' object is not iterable / None / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\Methods\RandomGraphUtils.py: linea 93 / setPointsGroup]
TypeError_10/09/2025_2159: ['NoneType' object is not iterable / 'NoneType' object is not iterable / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\Methods\GraphVisualizer.py: linea 29 / plotPointsAndDistances3D]
TypeError_10/09/2025_5134: [object of type 'NoneType' has no len() / object of type 'NoneType' has no len() / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Composables\MathReport.py: linea 103 / writeSystemsAndSolutions]
TypeError_10/09/2025_1215: [object of type 'NoneType' has no len() / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Storage\Results\d93af8b7_matriz1_d93af8b7.txt_20250910_352bd444.txt / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Composables\MathReport.py: linea 176 / writeDistancesBetweenPoints]
PermissionError_10/09/2025_6898: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
TypeError_10/09/2025_9480: ['NoneType' object is not iterable / randomGraph view / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\views.py: linea 72 / randomGraph]
PermissionError_10/09/2025_6436: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_2452: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_8674: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_9344: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
FileNotFoundError_10/09/2025_5882: [[Errno 2] No such file or directory: '.\\Apps\\DataProcessor\\DataExtractor\\Data\\datos_generados.txt' / randomGraph view / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\views.py: linea 33 / randomGraph]
PermissionError_10/09/2025_7014: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_3316: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_7986: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_5166: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_5862: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
FileNotFoundError_10/09/2025_9681: [[Errno 2] No such file or directory: '.\\Apps\\DataProcessor\\DataExtractor\\Data\\datos_generados.txt' / randomGraph view / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\views.py: linea 33 / randomGraph]
PermissionError_10/09/2025_4729: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_3703: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
SystemDontHaveSolution_10/09/2025_3092: [Error: El sistema de ecuaciones tiene soluciones infinitas o no tiene solución / coefficients_shape: (3, 3), independents_shape: (3,) / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\NumericalMethods\Solvers\MatrixOperators\SystemOfEquationsSolver.py: linea 160 / gaussJordanFullPivoting]
SystemDontHaveSolution_10/09/2025_8653: [Error: El sistema de ecuaciones tiene soluciones infinitas o no tiene solución / ['A', 'B', 'C'] / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\Methods\RandomGraphUtils.py: linea 81 / solvePoints]
TypeError_10/09/2025_7410: ['NoneType' object is not iterable / None / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\Methods\RandomGraphUtils.py: linea 93 / setPointsGroup]
TypeError_10/09/2025_6549: ['NoneType' object is not iterable / 'NoneType' object is not iterable / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\Methods\GraphVisualizer.py: linea 29 / plotPointsAndDistances3D]
TypeError_10/09/2025_3293: [object of type 'NoneType' has no len() / object of type 'NoneType' has no len() / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Composables\MathReport.py: linea 103 / writeSystemsAndSolutions]
TypeError_10/09/2025_7563: [object of type 'NoneType' has no len() / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Storage\Results\fa8b7275_matriz1_fa8b7275.txt_20250910_575fef80.txt / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Composables\MathReport.py: linea 176 / writeDistancesBetweenPoints]
PermissionError_10/09/2025_8119: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
TypeError_10/09/2025_1523: ['NoneType' object is not iterable / randomGraph view / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\views.py: linea 72 / randomGraph]
PermissionError_10/09/2025_1960: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_9849: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_4723: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_4200: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_7523: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
SystemDontHaveSolution_10/09/2025_3660: [Error: El sistema de ecuaciones tiene soluciones infinitas o no tiene solución / coefficients_shape: (3, 3), independents_shape: (3,) / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\NumericalMethods\Solvers\MatrixOperators\SystemOfEquationsSolver.py: linea 160 / gaussJordanFullPivoting]
SystemDontHaveSolution_10/09/2025_9560: [Error: El sistema de ecuaciones tiene soluciones infinitas o no tiene solución / ['A', 'B', 'C'] / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\Methods\RandomGraphUtils.py: linea 81 / solvePoints]
TypeError_10/09/2025_5345: ['NoneType' object is not iterable / None / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\Methods\RandomGraphUtils.py: linea 93 / setPointsGroup]
TypeError_10/09/2025_7823: ['NoneType' object is not iterable / 'NoneType' object is not iterable / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\Methods\GraphVisualizer.py: linea 29 / plotPointsAndDistances3D]
TypeError_10/09/2025_4534: [object of type 'NoneType' has no len() / object of type 'NoneType' has no len() / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Composables\MathReport.py: linea 103 / writeSystemsAndSolutions]
TypeError_10/09/2025_9877: [object of type 'NoneType' has no len() / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Storage\Results\a3912b95_matriz1_a3912b95.txt_20250910_687049c7.txt / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Composables\MathReport.py: linea 176 / writeDistancesBetweenPoints]
PermissionError_10/09/2025_5808: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
TypeError_10/09/2025_9746: ['NoneType' object is not iterable / randomGraph view / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\views.py: linea 72 / randomGraph]
PermissionError_10/09/2025_7419: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_1007: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_6540: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_7969: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_3560: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_6674: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_8671: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_1095: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
SystemDontHaveSolution_10/09/2025_8699: [Error: El sistema de ecuaciones tiene soluciones infinitas o no tiene solución / coefficients_shape: (3, 3), independents_shape: (3,) / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\NumericalMethods\Solvers\MatrixOperators\SystemOfEquationsSolver.py: linea 160 / gaussJordanFullPivoting]
SystemDontHaveSolution_10/09/2025_6880: [Error: El sistema de ecuaciones tiene soluciones infinitas o no tiene solución / ['A', 'B', 'C'] / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\Methods\RandomGraphUtils.py: linea 81 / solvePoints]
TypeError_10/09/2025_5447: ['NoneType' object is not iterable / None / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\Methods\RandomGraphUtils.py: linea 93 / setPointsGroup]
TypeError_10/09/2025_9522: ['NoneType' object is not iterable / 'NoneType' object is not iterable / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\Methods\GraphVisualizer.py: linea 29 / plotPointsAndDistances3D]
TypeError_10/09/2025_9560: [object of type 'NoneType' has no len() / object of type 'NoneType' has no len() / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Composables\MathReport.py: linea 103 / writeSystemsAndSolutions]
TypeError_10/09/2025_7919: [object of type 'NoneType' has no len() / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Storage\Results\19fb0f4d_matriz1_19fb0f4d.txt_20250910_a46db1c9.txt / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Composables\MathReport.py: linea 176 / writeDistancesBetweenPoints]
PermissionError_10/09/2025_3620: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
TypeError_10/09/2025_5644: ['NoneType' object is not iterable / randomGraph view / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\views.py: linea 72 / randomGraph]
PermissionError_10/09/2025_1140: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_8078: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_1133: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_6321: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_2299: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_4830: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_8577: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_7273: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_3544: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_1473: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_6415: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
UnboundLocalError_10/09/2025_9250: [cannot access local variable 'errors' where it is not associated with a value / randomGraph view / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\views.py: linea 132 / randomGraph]
PermissionError_10/09/2025_9468: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
UnboundLocalError_10/09/2025_4564: [cannot access local variable 'errors' where it is not associated with a value / randomGraph view / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\views.py: linea 132 / randomGraph]
PermissionError_10/09/2025_3880: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
UnboundLocalError_10/09/2025_4507: [cannot access local variable 'errors' where it is not associated with a value / randomGraph view / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\views.py: linea 132 / randomGraph]
PermissionError_10/09/2025_4890: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_2717: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_6432: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_2297: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_6483: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_7657: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
TypeError_10/09/2025_7540: [unsupported operand type(s) for -: 'NoneType' and 'NoneType' / randomGraph view / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\views.py: linea 48 / randomGraph]
PermissionError_10/09/2025_3233: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_1747: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_5536: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_9409: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_1465: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_9344: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
TypeError_10/09/2025_8553: [unsupported operand type(s) for -: 'NoneType' and 'NoneType' / randomGraph view / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\views.py: linea 48 / randomGraph]
PermissionError_10/09/2025_5073: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_5556: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_8953: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_5365: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_3116: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_8953: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
OSError_10/09/2025_1859: [wkhtmltopdf reported an error:
Exit with code 1 due to network error: ContentNotFoundError
 / randomGraph view / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\DataVisualization\views.py: linea 95 / randomGraph]
PermissionError_10/09/2025_8905: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_5075: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_3805: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_8258: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_4084: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_4072: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_8754: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_6559: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_2562: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_2257: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_1550: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_9989: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_9168: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_6111: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_6628: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_1666: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_4690: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_7977: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_6246: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_9281: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_9830: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_1295: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_2747: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_4210: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_7523: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_2451: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_5543: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_7984: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_4485: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_7321: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_4866: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_4644: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_8294: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_5788: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_2211: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_9575: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_4823: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_7447: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_8981: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_4397: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_5533: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_2563: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_7625: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_8633: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_6872: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_7060: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_3573: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_1203: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_4017: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_8696: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_2779: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_8963: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_1600: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_2238: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_1602: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_2837: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_4137: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_4112: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_5507: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_3916: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_4478: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_6227: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_5142: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_9878: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_5284: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_5994: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_1615: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_1394: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_4373: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_5416: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_7088: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_2027: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_9145: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_2706: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_1407: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_3919: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_7503: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
PermissionError_10/09/2025_1140: [[Errno 13] Permission denied: 'Apps\\Common\\Repositories\\Errors' / SystemOfEquationsSolver.__init__ / C:\Users\Admin\Desktop\CalculoPrivado\Jose\Testeo-Matematico\Apps\Common\Repositories\Errors\NumberofErrors.py: linea 7 / contador]
